# Generated by Django 3.2.3 on 2021-06-02 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_grower_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='grower',
            name='market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='markets.market'),
        ),
    ]
